--1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND REGION TABLE
select COUNTRY_NAME, REGION_NAME
from COUNTRIES
left join REGIONS
on REGIONS.REGION_ID = COUNTRIES.REGION_ID;

--2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
select FIRST_NAME, JOB_TITLE
from EMPLOYEES left join JOBS
on JOBS.JOB_ID = EMPLOYEES.JOB_ID;

--3. FIND OUT DEPARTMENT_NAME AND CITY
select DEPARTMENT_NAME, CITY
from DEPARTMENTS left join LOCATIONS
on LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID;

--4. FIND OUT ALL CITIES AND COUNTRY NAMES
select CITY, COUNTRY_NAME
from LOCATIONS full outer join COUNTRIES
on COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID;

--5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME FOR DEPARTMENT ID 80 OR 40
select FIRST_NAME, LAST_NAME, e.DEPARTMENT_ID, DEPARTMENT_NAME
from EMPLOYEES e left join DEPARTMENTS d
on e.DEPARTMENT_ID = d.DEPARTMENT_ID
where e.DEPARTMENT_ID in (80, 40);

-- 6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
select CITY, COUNTRY_NAME, REGION_NAME
from LOCATIONS left join COUNTRIES
on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
left join REGIONS
on COUNTRIES.REGION_ID = REGIONS.REGION_ID;

-- 7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
-- employee - jobs
-- employee - departments
-- departments - locations
select FIRST_NAME, JOB_TITLE, DEPARTMENT_NAME, CITY
from EMPLOYEES left join JOBS
on JOBS.JOB_ID = EMPLOYEES.JOB_ID
left join DEPARTMENTS
on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
left join LOCATIONS
on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;

-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY ,COUNTRY_NAME , REGION_NAME
-- //first table:
-- employee - jobs
-- employee - departments
-- //second table:
-- departments - location
-- location - countries
-- countries - region

select FIRST_NAME, JOB_TITLE, DEPARTMENT_NAME, CITY, COUNTRY_NAME, REGION_NAME
from EMPLOYEES left join JOBS
on EMPLOYEES.JOB_ID = JOBS.JOB_ID
left join DEPARTMENTS
on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
left join LOCATIONS
on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
left join COUNTRIES
on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
left join REGIONS
on COUNTRIES.REGION_ID = REGIONS.REGION_ID;

-- 9. FIND OUR EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL DEPARTMENTS INCLUDING WHERE DO NOT HAVE ANY EMPLOYEE.
select FIRST_NAME, LAST_NAME, EMPLOYEES.DEPARTMENT_ID, DEPARTMENT_NAME
from EMPLOYEES full join DEPARTMENTS
on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

-- 10. FIND OUT ALL DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_ID INCLUDING THOSE LOCATIONS WITH NO DEPARTMENT
select DEPARTMENT_NAME, LOCATIONS.LOCATION_ID, COUNTRY_ID
from DEPARTMENTS full join LOCATIONS
on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;

-- 11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT
select DEPARTMENT_NAME, LOCATIONS.LOCATION_ID, COUNTRY_NAME
from DEPARTMENTS full join LOCATIONS
on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
full join COUNTRIES
on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID;

-- 12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT NAME INCLUDING THOSE DOES NOT HAVE DEPARTMENT, INCLUDING THOSE
-- DEPARTMENTS DOES NOT HAVE ANY MATCHING EMPLOYEES
select FIRST_NAME, DEPARTMENTS.DEPARTMENT_ID, DEPARTMENT_NAME
from EMPLOYEES full join DEPARTMENTS
on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;